# -*- coding: utf-8 -*-
"""CIE

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y-SVptncnw-5GinYE-gakhPPKjTc0FuI
"""

import pandas as pd
data = pd.read_csv("/content/mtcars.csv")
print(data)

import matplotlib.pyplot as plt
plt.hist(data['mpg'], bins=10, color='skyblue', edgecolor='black')
plt.title('Frequency Distribution of Miles per Gallon (mpg)')
plt.xlabel('Miles per Gallon (mpg)')
plt.ylabel('Frequency')
plt.grid()
plt.show()

import matplotlib.pyplot as plt
plt.scatter(data['wt'],data['mpg'],color='r',alpha=0.5)
plt.title('relation between weight of the car and mpg')
plt.xlabel('Miles per Gallon (mpg)')
plt.ylabel('weight of the car')
plt.grid()
plt.show()

import matplotlib.pyplot as plt
tc=data.groupby('manufacturer').size().nlargest(5)
tc.plot(kind='bar',color='r')
plt.title('types of cars')
plt.xlabel('manufacturer')
plt.ylabel('cars')
plt.grid()
plt.show()

import matplotlib.pyplot as plt
data.boxplot(column='mpg',by='cyl',color='blue')
plt.title('boxplot')
plt.xlabel('mpg')
plt.ylabel('cyl')
plt.grid()
plt.show()